version: 1.0.{build}

image: Visual Studio 2019

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU

Configuration: Debug

build:
    parallel: true
    project: CI_TEST.sln
    publish_wap: true
    verbosity: normal
    

test:
  # only assemblies to test
  assemblies:
    only:
      - '**\*.Not-Dot-Test.dll'
      
test_script:
  xunit.console.clr4 "C:\projects\ci-test-app\CI_TEST\Not-Dot-Test" /appveyor