version: 1.0.{build}

image: Visual Studio 2019

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU


build:
    parallel: true
    project: \CI_TEST\CI_TEST.sln
    publish_wap: true
    verbosity: minimal


test:
  # only assemblies to test
  assemblies:
    only:
      - '**\*.Not-Dot-Test.dll'
      
  
artifacts:
  - path: '*.7z'
  