version: 1.0.{build}

image: Visual Studio 2015

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform: Any CPU

services:
  - mssql2014 

build:
    parallel: true
    project: \CI_TEST\CI_TEST.sln
    publish_wap: true
    verbosity: minimal


test:
  # only assemblies to test
  assemblies:
    
test_script:
    - '%xunit20%\xunit.console.x86 "%APPVEYOR_BUILD_FOLDER%\CI_TEST\Not-Dot-Test\bin\Debug\Not-Dot-Test.dll"  -appveyor'  
    


on_success:
    - ps: Write-host "Testing IP"
    - ps: if (!(Test-Connection 127.0.0.1)){ throw "Connection is not live"  }
    - ps: Write-host "Testing URL"
    - ps: try { $R = Invoke-WebRequest -URI http://TOTALLNOTAWEBSITE1231234235.com } catch { throw "Could not find website!"}


  